"""SensitiveGuard: context-aware privacy enforcement for smolagents workflows."""

from .agent import PrivacyContextBuilder, SensitiveDataAgent, SensitiveToolCallingAgent
from .audit import AuditLogger
from .detector import (
    PII_LABELS,
    CompositeDetector,
    Detector,
    GLiNERDetector,
    InjectionDetector,
    RegexDetector,
    SecretDetector,
)
from .eval import (
    AgentEvalSample,
    AgentEvaluator,
    AgentMetrics,
    Baseline,
    BaselineConfig,
    BaselineName,
    BenchmarkName,
    EntityEvaluator,
    EntityMetrics,
    EntitySpan,
    PRFScore,
)
from .factory import SensitiveGuardRuntime, create_sensitive_agent
from .mcp import MCPGateway, MCPSchemaValidator, TrustStore
from .memory import MemoryGuard, SanitizedMemoryStore
from .models import (
    Action,
    DecisionSet,
    DetectionResult,
    Finding,
    GuardResult,
    GuardStage,
    GuardStatus,
    PolicyDecision,
    Severity,
)
from .multiagent import GuardedAgentManager, GuardedWorker, HandoffGuard
from .policy import PolicyEngine, PolicyRule
from .privacy import DisclosureLedger, NecessityChecker, PrivacyContext, RiskEngine
from .runtime import (
    AcquisitionPlan,
    ApprovalRequest,
    ApprovalStore,
    AuthorizationPolicy,
    DataAcquisitionGuard,
    FinalOutputGuard,
    ObservationGuard,
    SafeToolGateway,
    ToolInputGuard,
    ToolRegistry,
)
from .transform import Pseudonymizer, TokenVault, TransformationEngine


__all__ = [
    "AcquisitionPlan",
    "Action",
    "AgentEvalSample",
    "AgentEvaluator",
    "AgentMetrics",
    "ApprovalRequest",
    "ApprovalStore",
    "AuditLogger",
    "AuthorizationPolicy",
    "Baseline",
    "BaselineConfig",
    "BaselineName",
    "BenchmarkName",
    "CompositeDetector",
    "DataAcquisitionGuard",
    "DecisionSet",
    "DetectionResult",
    "Detector",
    "DisclosureLedger",
    "EntityEvaluator",
    "EntityMetrics",
    "EntitySpan",
    "Finding",
    "FinalOutputGuard",
    "GLiNERDetector",
    "GuardResult",
    "GuardStage",
    "GuardStatus",
    "GuardedAgentManager",
    "GuardedWorker",
    "HandoffGuard",
    "InjectionDetector",
    "MCPGateway",
    "MCPSchemaValidator",
    "MemoryGuard",
    "NecessityChecker",
    "ObservationGuard",
    "PII_LABELS",
    "PolicyDecision",
    "PolicyEngine",
    "PolicyRule",
    "PRFScore",
    "PrivacyContext",
    "PrivacyContextBuilder",
    "Pseudonymizer",
    "RegexDetector",
    "RiskEngine",
    "SafeToolGateway",
    "SanitizedMemoryStore",
    "SecretDetector",
    "SensitiveDataAgent",
    "SensitiveGuardRuntime",
    "SensitiveToolCallingAgent",
    "Severity",
    "TokenVault",
    "ToolInputGuard",
    "ToolRegistry",
    "TransformationEngine",
    "TrustStore",
    "create_sensitive_agent",
]
