"""SensitiveGuard: context-aware privacy enforcement for smolagents workflows."""

from .agent import PrivacyContextBuilder, SensitiveDataAgent, SensitiveToolCallingAgent
from .audit import AuditLogger
from .detector import (
    PII_LABELS,
    CompositeDetector,
    Detector,
    EncodedPayloadDetector,
    GLiNERDetector,
    InjectionDetector,
    NormalizationDetector,
    RegexDetector,
    SecretDetector,
)
from .eval import (
    AgentEvalSample,
    AgentEvaluator,
    AgentMetrics,
    Baseline,
    BaselineConfig,
    BaselineName,
    BenchmarkName,
    EntityEvaluator,
    EntityMetrics,
    EntitySpan,
    PRFScore,
)
from .factory import SensitiveGuardRuntime, create_sensitive_agent
from .intent import (
    ActionRequest,
    Effect,
    IntentDecision,
    IntentGuard,
    IntentOperation,
    IntentResolver,
    IntentSpec,
    RuleBasedIntentResolver,
)
from .lineage import (
    ArtifactNode,
    ArtifactRole,
    GuardLineageRecord,
    LineageEvent,
    LineageEventType,
    LineageReport,
    LineageTracker,
    OperationStatus,
)
from .mcp import MCPGateway, MCPSchemaValidator, TrustStore
from .memory import MemoryGuard, SanitizedMemoryStore
from .models import (
    Action,
    DecisionSet,
    DetectionResult,
    Finding,
    GuardResult,
    GuardStage,
    GuardStatus,
    PolicyDecision,
    Severity,
)
from .multiagent import GuardedAgentManager, GuardedWorker, HandoffGuard
from .policy import PolicyEngine, PolicyRule
from .privacy import DisclosureLedger, NecessityChecker, PrivacyContext, RiskEngine
from .review import ExecutionPermit, ExecutionPermitStore, SecurityReviewEngine, SecurityReviewResult
from .routing import EndpointDescriptor, PrivacyRouter, RouteDecision, RouteKind, RouteStatus
from .runtime import (
    AcquisitionPlan,
    ApprovalRequest,
    ApprovalStore,
    AuthorizationPolicy,
    AuthorizedCommand,
    AuthorizedPath,
    CapabilityManifest,
    CapabilityManifestRegistry,
    CommandArgumentRule,
    CommandAuthorizationError,
    CommandAuthorizer,
    CommandCapability,
    CommandError,
    CommandExecutionResult,
    CommandExecutor,
    CommandExecutorError,
    CommandParseError,
    CommandParser,
    CommandPathAccess,
    CommandRequest,
    DataAcquisitionGuard,
    ExecutableIdentity,
    FinalOutputGuard,
    ObservationGuard,
    SafeToolGateway,
    ToolInputGuard,
    ToolRegistry,
    fingerprint_command,
)
from .tools import SafeCommandTool, SafeRunCommandTool, SafeShellTool, ToolExecutionOutcome, TraceDataLineageTool
from .transform import Pseudonymizer, TokenVault, TransformationEngine


__all__ = [
    "AcquisitionPlan",
    "Action",
    "ActionRequest",
    "AgentEvalSample",
    "AgentEvaluator",
    "AgentMetrics",
    "ApprovalRequest",
    "ApprovalStore",
    "ArtifactNode",
    "ArtifactRole",
    "AuditLogger",
    "AuthorizedCommand",
    "AuthorizedPath",
    "AuthorizationPolicy",
    "Baseline",
    "BaselineConfig",
    "BaselineName",
    "BenchmarkName",
    "CompositeDetector",
    "CapabilityManifest",
    "CapabilityManifestRegistry",
    "CommandArgumentRule",
    "CommandAuthorizationError",
    "CommandAuthorizer",
    "CommandCapability",
    "CommandError",
    "CommandExecutionResult",
    "CommandExecutor",
    "CommandExecutorError",
    "CommandParseError",
    "CommandParser",
    "CommandPathAccess",
    "CommandRequest",
    "DataAcquisitionGuard",
    "DecisionSet",
    "DetectionResult",
    "Detector",
    "DisclosureLedger",
    "Effect",
    "EncodedPayloadDetector",
    "EndpointDescriptor",
    "EntityEvaluator",
    "EntityMetrics",
    "EntitySpan",
    "ExecutableIdentity",
    "Finding",
    "FinalOutputGuard",
    "GLiNERDetector",
    "GuardResult",
    "GuardStage",
    "GuardStatus",
    "GuardLineageRecord",
    "GuardedAgentManager",
    "GuardedWorker",
    "HandoffGuard",
    "InjectionDetector",
    "IntentDecision",
    "IntentGuard",
    "IntentOperation",
    "IntentResolver",
    "IntentSpec",
    "LineageEvent",
    "LineageEventType",
    "LineageReport",
    "LineageTracker",
    "MCPGateway",
    "MCPSchemaValidator",
    "MemoryGuard",
    "NecessityChecker",
    "NormalizationDetector",
    "ObservationGuard",
    "OperationStatus",
    "PII_LABELS",
    "PolicyDecision",
    "PolicyEngine",
    "PolicyRule",
    "PRFScore",
    "PrivacyContext",
    "PrivacyContextBuilder",
    "PrivacyRouter",
    "Pseudonymizer",
    "RegexDetector",
    "RiskEngine",
    "RouteDecision",
    "RouteKind",
    "RouteStatus",
    "RuleBasedIntentResolver",
    "SafeCommandTool",
    "SafeRunCommandTool",
    "SafeShellTool",
    "SafeToolGateway",
    "SanitizedMemoryStore",
    "SecretDetector",
    "SensitiveDataAgent",
    "SensitiveGuardRuntime",
    "SensitiveToolCallingAgent",
    "SecurityReviewEngine",
    "SecurityReviewResult",
    "Severity",
    "TokenVault",
    "ToolInputGuard",
    "ToolExecutionOutcome",
    "ToolRegistry",
    "TraceDataLineageTool",
    "TransformationEngine",
    "TrustStore",
    "ExecutionPermit",
    "ExecutionPermitStore",
    "create_sensitive_agent",
    "fingerprint_command",
]
